[package]
name = "rust_timer_test"
version = "0.1.0"
authors = ["Tim de Jager <tdejager@smart-robotics.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.22"
tokio-os-timer = "0.1.7"
